name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
              env:
                MONGODB_URI: ${{secrets.MONGODB_URI}}
                JWT_SECRET: ${{secrets.JWT_SECRET}}
                ADZUNA_APP_ID: ${{secrets.ADZUNA_APP_ID}}
                ADZUNA_APP_KEY: ${{secrets.ADZUNA_APP_KEY}}